/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChecklistsIndexRouteImport } from './routes/checklists/index'
import { Route as ChecklistsCreateRouteImport } from './routes/checklists/create'
import { Route as ChecklistsIdRouteImport } from './routes/checklists/$id'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsIndexRoute = ChecklistsIndexRouteImport.update({
  id: '/checklists/',
  path: '/checklists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsCreateRoute = ChecklistsCreateRouteImport.update({
  id: '/checklists/create',
  path: '/checklists/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsIdRoute = ChecklistsIdRouteImport.update({
  id: '/checklists/$id',
  path: '/checklists/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/checklists/$id': typeof ChecklistsIdRoute
  '/checklists/create': typeof ChecklistsCreateRoute
  '/checklists/': typeof ChecklistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/checklists/$id': typeof ChecklistsIdRoute
  '/checklists/create': typeof ChecklistsCreateRoute
  '/checklists': typeof ChecklistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/checklists/$id': typeof ChecklistsIdRoute
  '/checklists/create': typeof ChecklistsCreateRoute
  '/checklists/': typeof ChecklistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/checklists/$id'
    | '/checklists/create'
    | '/checklists/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/checklists/$id' | '/checklists/create' | '/checklists'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/checklists/$id'
    | '/checklists/create'
    | '/checklists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  ChecklistsIdRoute: typeof ChecklistsIdRoute
  ChecklistsCreateRoute: typeof ChecklistsCreateRoute
  ChecklistsIndexRoute: typeof ChecklistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists/': {
      id: '/checklists/'
      path: '/checklists'
      fullPath: '/checklists/'
      preLoaderRoute: typeof ChecklistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists/create': {
      id: '/checklists/create'
      path: '/checklists/create'
      fullPath: '/checklists/create'
      preLoaderRoute: typeof ChecklistsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists/$id': {
      id: '/checklists/$id'
      path: '/checklists/$id'
      fullPath: '/checklists/$id'
      preLoaderRoute: typeof ChecklistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  ChecklistsIdRoute: ChecklistsIdRoute,
  ChecklistsCreateRoute: ChecklistsCreateRoute,
  ChecklistsIndexRoute: ChecklistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
